# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/nahua/Unreal/unreal5.2.1
GAMEPROJECTFILE =/home/nahua/Documents/Unreal Projects/UnrealCourse/UnrealCourse.uproject

TARGETS = \
	UnrealCourse-Linux-DebugGame  \
	UnrealCourse-Linux-Shipping  \
	UnrealCourse \
	UnrealCourseEditor-Linux-DebugGame  \
	UnrealCourseEditor-Linux-Shipping  \
	UnrealCourseEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealCourseEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealCourseEditor-Linux-Debug


UnrealCourse-Linux-DebugGame:
	 $(PROJECTBUILD) UnrealCourse Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCourse-Linux-Shipping:
	 $(PROJECTBUILD) UnrealCourse Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCourse:
	 $(PROJECTBUILD) UnrealCourse Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCourseEditor-Linux-DebugGame:
	 $(PROJECTBUILD) UnrealCourseEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCourseEditor-Linux-Shipping:
	 $(PROJECTBUILD) UnrealCourseEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCourseEditor:
	 $(PROJECTBUILD) UnrealCourseEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
